application: glass-upload
version: 1
runtime: python27
threadsafe: true
api_version: 1

default_expiration: '3650d'

builtins:
- remote_api: on
- appstats: on

error_handlers:
  - file: templates/generic_error.html
  - error_code: over_quota
    file: templates/over_quota.html

libraries:
- name: django
  version: latest

inbound_services:
- channel_presence


handlers:
- url: /(robots\.txt|favicon\.ico)
  static_files: static/\1
  upload: static/(.*)

- url: /css
  static_dir: static/css
  secure: always

- url: /js
  static_dir: static/js
  secure: always

- url: /images
  static_dir: static/images
  secure: always

- url: /img
  static_dir: static/images
  secure: always

- url: /static
  static_dir: static
  secure: always

- url: /god/.*
  script: god.god
  login: admin
  secure: always

- url: .*
  script: main.application
  secure: always

